# Generated by Django 3.1.5 on 2021-01-08 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollectedPR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=255, verbose_name='PR url')),
                ('pr_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pr_by', to='main.githubuser')),
            ],
            options={
                'verbose_name_plural': 'Github Users',
            },
        ),
    ]
